name: Run reverse image finder

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: "Image URL"
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run main.py
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: |
          echo "${{ inputs.image_url }}" | python main.py
